name: ClassNet
arch:
  type: Model
  backbone:
    type: resnet18
    pretrained: true
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: ClassHead
    out_channels: 4
trainer:
  seed: 2
  epochs: 3
  log_iter: 1
  show_images_iter: 500
  resume_checkpoint: ''
  finetune_checkpoint: ''
  output_dir: output

