name: ClassNet
arch:
  type: Model
  backbone:
    type: resnet18
    pretrained: true
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: ClassHead
    out_channels: 4
trainer:
  seed: 29
  epochs: 100
  log_iter: 1
  show_images_iter: 500
  resume_checkpoint: 'model.pth'   #'model.pth'
  finetune_checkpoint: ''    #'model.pth'
  output_dir: output

