name: ClassNet
arch:
  type: Model
  backbone:
    type: resnet18
    pretrained: true
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: ClassHead
    out_channels: 4
trainer:
  seed: 29
  epochs: 10
  log_iter: 1
  show_images_iter: 500
  resume_checkpoint: 'output/model.pth'   # 'output/model.pth'
  # finetune_checkpoint: ''    #'model.pth'
  output_dir: output
  lr: 0.000001  # 0.00001
  weight_decay: 0.001

